export const SUPPORTED_CURRENCIES = [
  {
    name: 'Vietnamese Dong',
    code: 'VND',
    symbol: '₫',
    symbolBefore: false,
    decimalDigits: 0,
    rounding: 0,
    i18n: 'currency.vnd',
  },
  {
    name: 'U.S. Dollar',
    code: 'USD',
    symbol: '$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.usd',
  },
  {
    name: 'Euro',
    code: 'EUR',
    symbol: '€',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.eur',
  },
  {
    name: 'British Pound',
    code: 'GBP',
    symbol: '£',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.gbp',
  },
  {
    name: 'Japanese Yen',
    code: 'JPY',
    symbol: '¥',
    symbolBefore: true,
    decimalDigits: 0,
    rounding: 0,
    i18n: 'currency.jpy',
  },
  {
    name: 'Canadian Dollar',
    code: 'CAD',
    symbol: 'C$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.cad',
  },
  {
    name: 'Australian Dollar',
    code: 'AUD',
    symbol: 'A$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.aud',
  },
  {
    name: 'Singapore Dollar',
    code: 'SGD',
    symbol: 'S$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.sgd',
  },
  {
    name: 'Swiss Franc',
    code: 'CHF',
    symbol: 'CHF',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.chf',
  },
  {
    name: 'Chinese Yuan',
    code: 'CNY',
    symbol: '¥',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.cny',
  },
  {
    name: 'Hong Kong Dollar',
    code: 'HKD',
    symbol: 'HK$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.hkd',
  },
  {
    name: 'New Zealand Dollar',
    code: 'NZD',
    symbol: 'NZ$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.nzd',
  },
  {
    name: 'South Korean Won',
    code: 'KRW',
    symbol: '₩',
    symbolBefore: true,
    decimalDigits: 0,
    rounding: 0,
    i18n: 'currency.krw',
  },
  {
    name: 'Indian Rupee',
    code: 'INR',
    symbol: '₹',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.inr',
  },
  {
    name: 'Thai Baht',
    code: 'THB',
    symbol: '฿',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.thb',
  },
  {
    name: 'Indonesian Rupiah',
    code: 'IDR',
    symbol: 'Rp',
    symbolBefore: true,
    decimalDigits: 0,
    rounding: 0,
    i18n: 'currency.idr',
  },
  {
    name: 'Philippine Peso',
    code: 'PHP',
    symbol: '₱',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.php',
  },
  {
    name: 'Malaysian Ringgit',
    code: 'MYR',
    symbol: 'RM',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.myr',
  },
  {
    name: 'Taiwan Dollar',
    code: 'TWD',
    symbol: 'NT$',
    symbolBefore: true,
    decimalDigits: 2,
    rounding: 0,
    i18n: 'currency.twd',
  },
]
