import type { icons } from 'lucide-react-native'

export const CATEGORY_EXPENSE_ICONS: Array<keyof typeof icons> = [
  'WalletMinimal',
  'Coins',
  'Banknote',
  'Bitcoin',
  'CreditCard',
  'Gem',
  'HandCoins',
  'Handshake',
  'PiggyBank',
  'SmartphoneNfc',
  'BadgeCent',
  'BadgeDollarSign',
  'BadgeEuro',
  'BadgeIndianRupee',
  'BadgeJapaneseYen',
  'BadgePoundSterling',
  'BadgeRussianRuble',
  'BadgeSwissFranc',
  // 'Paintbrush',
  // 'BrickWall',
  // 'CookingPot',
]

export const CATEGORY_INCOME_ICONS: Array<keyof typeof icons> = [
  'WalletMinimal',
  'Coins',
  'Banknote',
  'Bitcoin',
  'CreditCard',
  'Gem',
  'HandCoins',
  'Handshake',
  'PiggyBank',
  'SmartphoneNfc',
  'BadgeCent',
  'BadgeDollarSign',
  'BadgeEuro',
  'BadgeIndianRupee',
  'BadgeJapaneseYen',
  'BadgePoundSterling',
  'BadgeRussianRuble',
  'BadgeSwissFranc',
  // 'Paintbrush',
  // 'BrickWall',
  // 'CookingPot',
].reverse() as Array<keyof typeof icons>
